---
title: "Visualize data"
author: "Isaac Verminck"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}

# rm(list = ls())

library(knitr)

opts_chunk$set(echo=TRUE,
               warning=FALSE,
               message=FALSE,
               cache=FALSE)

devtools::load_all(here::here())

```

```{r load_data}

load(file = paste(data_path, "year_of_birth.RData", sep = "/"))


```

# Visualize data

## At what age do people marry?

For a start, let's not focus on any specific regions and have a look at the most recent data. How is the number of marriages distributed among the ages?

```{r bar_age_marriage}
recent_marriage <- year_of_birth %>%
  dplyr::filter(year == "2014") %>% 
  dplyr::filter(type == "marriage")


recent_marriage_belgium <- recent_marriage %>%
  dplyr::filter(region == "belgium") 

ggplot2::ggplot(data = recent_marriage_belgium, ggplot2::aes(x = age, y = quantity)) +
  ggplot2::geom_line(group = 1) +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))


```

Most people marry in the end of their twenties. Is there a regional difference?

```{r regional_difference_age_marriage}
ggplot2::ggplot(data = recent_marriage, ggplot2::aes(x = age, y = quantity)) +
  ggplot2::geom_line(ggplot2::aes(color = region), group = 1) +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, hjust = 1))

```

